import { ScoreDial } from "./ScoreDial";

type MetaChip = { label: string; value: string };

const DEFAULT_CATEGORY_BENCHMARK = 38;

function benchmarkCaption(score: number, benchmark: number): string {
  if (score > benchmark) return `above typical category benchmark (${benchmark})`;
  if (score < benchmark) return `below typical category benchmark (${benchmark})`;
  return `at typical category benchmark (${benchmark})`;
}

export function ReportHero({
  brandName,
  urlHost,
  locale,
  promptCount,
  engineCount,
  competitorCount,
  score,
  /** Reference score for the subtitle line (industry placeholder until real benchmarks exist). */
  categoryBenchmark = DEFAULT_CATEGORY_BENCHMARK,
  variant = "private",
  generatedAt,
}: {
  brandName: string;
  urlHost: string;
  locale: string;
  promptCount: number;
  engineCount: number;
  competitorCount: number;
  score: number | null | undefined;
  categoryBenchmark?: number;
  variant?: "private" | "public";
  generatedAt?: string;
}) {
  const s = score ?? 0;
  const bench = categoryBenchmark ?? DEFAULT_CATEGORY_BENCHMARK;

  const privateChips: MetaChip[] = [
    { label: "URL", value: urlHost },
    { label: "LOCALE", value: locale },
    { label: "PROMPTS", value: String(promptCount) },
    { label: "ENGINES", value: String(engineCount) },
    { label: "COMPETITORS", value: String(competitorCount) },
  ];
  const publicChips: MetaChip[] = [
    ...(generatedAt ? [{ label: "GENERATED", value: generatedAt }] : []),
    { label: "ENGINES", value: String(engineCount) },
    { label: "PROMPTS", value: String(promptCount) },
    { label: "LOCALE", value: locale },
    { label: "TOOL", value: "CitationPulse v1.0" },
  ];
  const chips = variant === "public" ? publicChips : privateChips;

  const title =
    variant === "public" ? (
      <>
        AI Citation Report <span className="text-brand-primaryBright">(public)</span>
      </>
    ) : (
      <>
        Your <span className="text-brand-primaryBright">multi-engine</span> citation report
      </>
    );

  const subtitle =
    variant === "public" ? (
      <>
        This report was generated by CitationPulse, a Traffic Radius product. It shows how this brand is being cited
        in answers from the five major AI engines — across the buyer questions they monitor.
      </>
    ) : (
      <>
        Here&apos;s how <strong className="text-white">{brandName}</strong> is being cited inside answers from
        ChatGPT, Claude, Perplexity, and Gemini — across every monitored prompt. Switch engines below to change the
        heatmap layer.
      </>
    );

  const isReportLayout = variant === "private";

  return (
    <section
      className={
        isReportLayout
          ? "rounded-b-[22px] bg-gradient-to-br from-tr-navy from-0% to-tr-navy2 to-100% px-6 py-9 text-white"
          : "overflow-hidden rounded-2xl bg-gradient-to-br from-tr-navy via-[#1a5a3a] to-tr-navyDeep p-8 text-white shadow-lift lg:p-10"
      }
    >
      <div
        className={
          isReportLayout
            ? "grid gap-8 lg:grid-cols-[1.5fr_360px] lg:items-center"
            : "flex flex-col gap-10 lg:flex-row lg:items-center lg:justify-between"
        }
      >
        <div className="max-w-2xl">
          <h1
            className={
              isReportLayout
                ? "font-display text-4xl font-black leading-[1.15] tracking-[-0.8px]"
                : "font-display text-3xl font-bold leading-tight tracking-tight lg:text-4xl"
            }
          >
            {title}
          </h1>
          {isReportLayout ? (
            <span className="report-head-under-mark mt-1.5 block" aria-hidden />
          ) : (
            <div className="title-underline max-w-sm opacity-90" />
          )}
          <p
            className={
              isReportLayout
                ? "mt-4 max-w-[660px] text-[14.5px] leading-relaxed text-white/90"
                : "mt-5 text-sm leading-relaxed text-slate-300 lg:text-base"
            }
          >
            {subtitle}
          </p>
          <div className="mt-4 flex flex-wrap gap-2.5">
            {chips.map((c) => (
              <div
                key={c.label}
                className="inline-flex items-center gap-2 rounded-lg border border-white/15 bg-white/[0.07] px-3 py-1.5 text-xs text-[#E6F4EC]"
              >
                <span className="rounded px-1.5 py-0.5 font-display text-[9px] font-extrabold uppercase tracking-wide text-brand-primaryBright bg-brand-primary/15">
                  {c.label}
                </span>
                {c.value}
              </div>
            ))}
          </div>
        </div>
        <div className="flex flex-wrap items-center justify-center gap-5 lg:justify-end">
          <ScoreDial score={s} size={110} stroke={9} centerScore strokeColor="#1FB36B" />
          <div className="text-left">
            <p className="font-display text-[10.5px] font-extrabold uppercase tracking-[1.2px] text-brand-primaryBright">
              Average citation score
            </p>
            <p className="mt-1 font-display text-[38px] font-black leading-none tabular-nums text-white">
              {s}
              <span className="text-lg font-bold text-white/60">/100</span>
            </p>
            <p className="mt-1.5 text-xs text-white/75">
              across {engineCount} engines · {benchmarkCaption(s, bench)}
            </p>
          </div>
        </div>
      </div>
    </section>
  );
}

